name: CI

on:
  push:
    branches:
    - "feature/**"
    - "bugfix/**"

  pull_request:
    types: [opened, reopened, assigned, synchronize]
    branches: [master, develop]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.3
        terraform_wrapper: false

    - name: Check Terraform format and syntax
      id: test
      run: make test