name: Draft a release

on: 
  workflow_dispatch:

jobs:
  draft-a-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Generate release tag
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=$(curl -s https://raw.githubusercontent.com/khanh-ph/github-actions-scripts/master/gen-next-semver/gen-next-semver.sh | sudo bash)
        echo VERSION=$VERSION >> $GITHUB_ENV
        echo BRANCH=release/$VERSION >> $GITHUB_ENV

    - name: Create release branch
      run: |
        git checkout -b ${{ env.BRANCH }}

    - name: Push release branch
      run: git push origin ${{ env.BRANCH }}

    - name: Create a pull request
      uses: thomaseizinger/create-pull-request@1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        head: ${{ env.BRANCH }}
        base: master
        title: Release version ${{ env.VERSION }}
 